# Generated by Django 6.0.7 on 2026-08-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definicao',
            fields=[
                ('chave', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('valor', models.JSONField()),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'definições',
                'db_table': 'definicoes',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favoritos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('url_externa', models.URLField(blank=True, max_length=500)),
                ('texto_alternativo', models.CharField(blank=True, max_length=200)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'imagens de produto',
                'db_table': 'imagens_produto',
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('assinatura', models.CharField(blank=True, max_length=160, verbose_name='posicionamento')),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='marcas/', verbose_name='imagem editorial')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='marcas/logos/')),
                ('destaque', models.BooleanField(default=False)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marcas',
                'ordering': ['posicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('nome', models.CharField(max_length=140)),
                ('descricao', models.TextField()),
                ('detalhes', models.TextField(blank=True, help_text='Um detalhe por linha.')),
                ('preco', models.PositiveIntegerField(verbose_name='preço (Kz)')),
                ('preco_anterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='preço anterior (Kz)')),
                ('distintivo', models.CharField(blank=True, choices=[('NOVO', 'Novo'), ('ULTIMAS_UNIDADES', 'Últimas unidades')], max_length=20)),
                ('novidade', models.BooleanField(default=False)),
                ('mais_vendido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('meta_titulo', models.CharField(blank=True, max_length=160)),
                ('meta_descricao', models.CharField(blank=True, max_length=320)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Subscritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('origem', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscritores',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=20)),
                ('cor_nome', models.CharField(max_length=40)),
                ('cor_hex', models.CharField(default='#111111', max_length=7)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('limiar_stock_baixo', models.PositiveIntegerField(default=6)),
                ('preco_proprio', models.PositiveIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'variantes',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'db_table': 'categorias',
                'ordering': ['posicao', 'nome'],
                'indexes': [models.Index(fields=['activa', 'posicao'], name='categorias_activa_b7ef3a_idx')],
            },
        ),
    ]
