# Generated by Django 6.0.7 on 2026-08-01 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['activa', 'posicao'], name='marcas_activa_48d479_idx'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['destaque'], name='marcas_destaqu_a34c5d_idx'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.marca'),
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.produto'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='catalogo.produto'),
        ),
        migrations.AddField(
            model_name='variante',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.produto'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['activo', '-criado_em'], name='produtos_activo_78f242_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['marca'], name='produtos_marca_i_f22ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='produtos_categor_79cde9_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['preco'], name='produtos_preco_7f62fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('utilizador', 'produto'), name='favorito_unico'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['stock'], name='variantes_stock_09b61a_idx'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('produto', 'tamanho', 'cor_nome'), name='variante_unica_por_produto'),
        ),
    ]
