# Generated by Django 6.0.7 on 2026-08-02 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('compra_verificada', models.BooleanField(default=True)),
                ('publicada', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalogo.produto')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'avaliações',
                'db_table': 'avaliacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.ImageField(blank=True, null=True, upload_to='avaliacoes/')),
                ('url_externa', models.URLField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='catalogo.avaliacao')),
            ],
            options={
                'verbose_name_plural': 'fotografias de avaliação',
                'db_table': 'fotos_avaliacao',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['produto', 'publicada'], name='avaliacoes_produto_173afe_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['-criado_em'], name='avaliacoes_criado__7c87ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('produto', 'utilizador'), name='avaliacao_unica_por_cliente'),
        ),
    ]
