# Generated by Django 6.0.7 on 2026-08-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_avaliacao_fotoavaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.PositiveIntegerField(verbose_name='preço anterior (Kz)')),
                ('preco_novo', models.PositiveIntegerField(verbose_name='preço novo (Kz)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='catalogo.produto')),
            ],
            options={
                'verbose_name_plural': 'histórico de preços',
                'db_table': 'historico_precos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['produto', '-criado_em'], name='historico_p_produto_4135a9_idx')],
            },
        ),
    ]
