# Generated by Django 6.0.7 on 2026-08-02 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_historicopreco'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaReposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('notificado_em', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_reposicao', to='catalogo.produto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='catalogo.variante')),
            ],
            options={
                'verbose_name_plural': 'alertas de reposição',
                'db_table': 'alertas_reposicao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['produto', 'notificado_em'], name='alertas_rep_produto_6a979a_idx')],
            },
        ),
    ]
