# Generated by Django 6.0.7 on 2026-08-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alertareposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='preço de custo (Kz)'),
        ),
    ]
