# Generated by Django 6.0.7 on 2026-08-01 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('PERCENT', 'Percentagem'), ('FIXED', 'Valor fixo')], default='PERCENT', max_length=10)),
                ('valor', models.PositiveIntegerField()),
                ('subtotal_minimo', models.PositiveIntegerField(blank=True, null=True)),
                ('max_utilizacoes', models.PositiveIntegerField(blank=True, null=True)),
                ('vezes_usado', models.PositiveIntegerField(default=0)),
                ('comeca_em', models.DateTimeField(blank=True, null=True)),
                ('termina_em', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'cupões',
                'db_table': 'cupoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_sessao', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('utilizador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20, unique=True)),
                ('nome_cliente', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('NOVA', 'Nova'), ('CONFIRMADA', 'Confirmada'), ('EM_PREPARACAO', 'Em preparação'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='NOVA', max_length=20)),
                ('subtotal', models.PositiveIntegerField()),
                ('envio', models.PositiveIntegerField(default=0)),
                ('desconto', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('provincia', models.CharField(max_length=60)),
                ('municipio', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=240)),
                ('observacoes', models.TextField(blank=True)),
                ('stock_reposto', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('cupao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas', to='encomendas.cupao')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encomendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('NOVA', 'Nova'), ('CONFIRMADA', 'Confirmada'), ('EM_PREPARACAO', 'Em preparação'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('estado_novo', models.CharField(choices=[('NOVA', 'Nova'), ('CONFIRMADA', 'Confirmada'), ('EM_PREPARACAO', 'Em preparação'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='encomendas.encomenda')),
            ],
            options={
                'db_table': 'eventos_encomenda',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='encomendas.carrinho')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='catalogo.variante')),
            ],
            options={
                'db_table': 'itens_carrinho',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=120)),
                ('nome_produto', models.CharField(max_length=140)),
                ('slug_produto', models.SlugField(max_length=180)),
                ('url_imagem', models.CharField(blank=True, max_length=500)),
                ('tamanho', models.CharField(max_length=20)),
                ('cor_nome', models.CharField(max_length=40)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('preco_unitario', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('total_linha', models.PositiveIntegerField()),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='encomendas.encomenda')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_encomenda', to='catalogo.variante')),
            ],
            options={
                'db_table': 'itens_encomenda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('FALHADO', 'Falhado')], default='PENDENTE', max_length=20)),
                ('montante', models.PositiveIntegerField()),
                ('moeda', models.CharField(default='AOA', max_length=3)),
                ('referencia', models.CharField(max_length=80, unique=True)),
                ('referencia_provedor', models.CharField(blank=True, max_length=120)),
                ('resposta_bruta', models.JSONField(blank=True, null=True)),
                ('motivo_falha', models.CharField(blank=True, max_length=300)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='encomendas.encomenda')),
            ],
            options={
                'db_table': 'pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='encomenda',
            index=models.Index(fields=['estado'], name='encomendas_estado_8af014_idx'),
        ),
        migrations.AddIndex(
            model_name='encomenda',
            index=models.Index(fields=['-criado_em'], name='encomendas_criado__1eabe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrinho',
            constraint=models.UniqueConstraint(fields=('carrinho', 'variante'), name='item_unico_no_carrinho'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['estado'], name='pagamentos_estado_a156ad_idx'),
        ),
    ]
