/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeTrocasRouteImport } from './routes/politica-de-trocas'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as ReporPasswordRouteImport } from './routes/repor-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCupoesRouteImport } from './routes/admin.cupoes'
import { Route as AdminEncomendasRouteImport } from './routes/admin.encomendas'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as ContaEncomendasRouteImport } from './routes/conta.encomendas'
import { Route as ContaFavoritosRouteImport } from './routes/conta.favoritos'
import { Route as ContaMoradasRouteImport } from './routes/conta.moradas'
import { Route as MarcasIndexRouteImport } from './routes/marcas.index'
import { Route as MarcasSlugRouteImport } from './routes/marcas.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocasRoute = PoliticaDeTrocasRouteImport.update({
  id: '/politica-de-trocas',
  path: '/politica-de-trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporPasswordRoute = ReporPasswordRouteImport.update({
  id: '/repor-password',
  path: '/repor-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCupoesRoute = AdminCupoesRouteImport.update({
  id: '/cupoes',
  path: '/cupoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEncomendasRoute = AdminEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const ContaEncomendasRoute = ContaEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => ContaRoute,
} as any)
const ContaFavoritosRoute = ContaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaMoradasRoute = ContaMoradasRouteImport.update({
  id: '/moradas',
  path: '/moradas',
  getParentRoute: () => ContaRoute,
} as any)
const MarcasIndexRoute = MarcasIndexRouteImport.update({
  id: '/marcas/',
  path: '/marcas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasSlugRoute = MarcasSlugRouteImport.update({
  id: '/marcas/$slug',
  path: '/marcas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/registo': typeof RegistoRoute
  '/repor-password': typeof ReporPasswordRoute
  '/shop': typeof ShopRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupoes': typeof AdminCupoesRoute
  '/admin/encomendas': typeof AdminEncomendasRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/stock': typeof AdminStockRoute
  '/conta/encomendas': typeof ContaEncomendasRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/moradas': typeof ContaMoradasRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/marcas/': typeof MarcasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/registo': typeof RegistoRoute
  '/repor-password': typeof ReporPasswordRoute
  '/shop': typeof ShopRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupoes': typeof AdminCupoesRoute
  '/admin/encomendas': typeof AdminEncomendasRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/stock': typeof AdminStockRoute
  '/conta/encomendas': typeof ContaEncomendasRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/moradas': typeof ContaMoradasRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/conta': typeof ContaIndexRoute
  '/marcas': typeof MarcasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/registo': typeof RegistoRoute
  '/repor-password': typeof ReporPasswordRoute
  '/shop': typeof ShopRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupoes': typeof AdminCupoesRoute
  '/admin/encomendas': typeof AdminEncomendasRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/stock': typeof AdminStockRoute
  '/conta/encomendas': typeof ContaEncomendasRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/moradas': typeof ContaMoradasRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/marcas/': typeof MarcasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contacto'
    | '/entrar'
    | '/faq'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/recuperar-password'
    | '/registo'
    | '/repor-password'
    | '/shop'
    | '/sobre'
    | '/termos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupoes'
    | '/admin/encomendas'
    | '/admin/marcas'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/stock'
    | '/conta/encomendas'
    | '/conta/favoritos'
    | '/conta/moradas'
    | '/marcas/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/conta/'
    | '/marcas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/contacto'
    | '/entrar'
    | '/faq'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/recuperar-password'
    | '/registo'
    | '/repor-password'
    | '/shop'
    | '/sobre'
    | '/termos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupoes'
    | '/admin/encomendas'
    | '/admin/marcas'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/stock'
    | '/conta/encomendas'
    | '/conta/favoritos'
    | '/conta/moradas'
    | '/marcas/$slug'
    | '/produto/$slug'
    | '/admin'
    | '/conta'
    | '/marcas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contacto'
    | '/entrar'
    | '/faq'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/recuperar-password'
    | '/registo'
    | '/repor-password'
    | '/shop'
    | '/sobre'
    | '/termos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupoes'
    | '/admin/encomendas'
    | '/admin/marcas'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/stock'
    | '/conta/encomendas'
    | '/conta/favoritos'
    | '/conta/moradas'
    | '/marcas/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/conta/'
    | '/marcas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  EntrarRoute: typeof EntrarRoute
  FaqRoute: typeof FaqRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeTrocasRoute: typeof PoliticaDeTrocasRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
  RegistoRoute: typeof RegistoRoute
  ReporPasswordRoute: typeof ReporPasswordRoute
  ShopRoute: typeof ShopRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  MarcasSlugRoute: typeof MarcasSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  MarcasIndexRoute: typeof MarcasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-trocas': {
      id: '/politica-de-trocas'
      path: '/politica-de-trocas'
      fullPath: '/politica-de-trocas'
      preLoaderRoute: typeof PoliticaDeTrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repor-password': {
      id: '/repor-password'
      path: '/repor-password'
      fullPath: '/repor-password'
      preLoaderRoute: typeof ReporPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupoes': {
      id: '/admin/cupoes'
      path: '/cupoes'
      fullPath: '/admin/cupoes'
      preLoaderRoute: typeof AdminCupoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/encomendas': {
      id: '/admin/encomendas'
      path: '/encomendas'
      fullPath: '/admin/encomendas'
      preLoaderRoute: typeof AdminEncomendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/encomendas': {
      id: '/conta/encomendas'
      path: '/encomendas'
      fullPath: '/conta/encomendas'
      preLoaderRoute: typeof ContaEncomendasRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/favoritos': {
      id: '/conta/favoritos'
      path: '/favoritos'
      fullPath: '/conta/favoritos'
      preLoaderRoute: typeof ContaFavoritosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/moradas': {
      id: '/conta/moradas'
      path: '/moradas'
      fullPath: '/conta/moradas'
      preLoaderRoute: typeof ContaMoradasRouteImport
      parentRoute: typeof ContaRoute
    }
    '/marcas/': {
      id: '/marcas/'
      path: '/marcas'
      fullPath: '/marcas/'
      preLoaderRoute: typeof MarcasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/$slug': {
      id: '/marcas/$slug'
      path: '/marcas/$slug'
      fullPath: '/marcas/$slug'
      preLoaderRoute: typeof MarcasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCupoesRoute: typeof AdminCupoesRoute
  AdminEncomendasRoute: typeof AdminEncomendasRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCupoesRoute: AdminCupoesRoute,
  AdminEncomendasRoute: AdminEncomendasRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminStockRoute: AdminStockRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContaRouteChildren {
  ContaEncomendasRoute: typeof ContaEncomendasRoute
  ContaFavoritosRoute: typeof ContaFavoritosRoute
  ContaMoradasRoute: typeof ContaMoradasRoute
  ContaIndexRoute: typeof ContaIndexRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaEncomendasRoute: ContaEncomendasRoute,
  ContaFavoritosRoute: ContaFavoritosRoute,
  ContaMoradasRoute: ContaMoradasRoute,
  ContaIndexRoute: ContaIndexRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRouteWithChildren,
  ContactoRoute: ContactoRoute,
  EntrarRoute: EntrarRoute,
  FaqRoute: FaqRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeTrocasRoute: PoliticaDeTrocasRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
  RegistoRoute: RegistoRoute,
  ReporPasswordRoute: ReporPasswordRoute,
  ShopRoute: ShopRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  MarcasSlugRoute: MarcasSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  MarcasIndexRoute: MarcasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
