# Generated by Django 6.0.7 on 2026-08-01 18:43

import contas.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('primeiro_nome', models.CharField(max_length=60, verbose_name='nome')),
                ('apelido', models.CharField(max_length=60, verbose_name='apelido')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('papel', models.CharField(choices=[('USER', 'Cliente'), ('ADMIN', 'Administrador')], default='USER', max_length=10)),
                ('aceita_marketing', models.BooleanField(default=True, verbose_name='aceita comunicações')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso administrativo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilizador',
                'verbose_name_plural': 'utilizadores',
                'db_table': 'utilizadores',
                'ordering': ['-criado_em'],
            },
            managers=[
                ('objects', contas.models.GestorUtilizador()),
            ],
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=40, verbose_name='nome da morada')),
                ('destinatario', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=60)),
                ('municipio', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=240)),
                ('observacoes', models.TextField(blank=True)),
                ('principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'moradas',
                'db_table': 'moradas',
                'ordering': ['-principal', 'criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='utilizador',
            index=models.Index(fields=['papel'], name='utilizadore_papel_41e51b_idx'),
        ),
    ]
